version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: ${APP_PATH_CONTAINER}
    networks:
      - www
  php:
    build: ./docker/php
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    networks:
      - www
networks:
  www:
    driver: bridge
volumes:
  mysql:
    driver: local