version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./www:/app
    networks:
      - www
networks:
  www:
    driver: bridge