FROM ubuntu:20.04

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN groupadd --force -g 1000 www \
    && useradd -ms /bin/bash --no-user-group -g 1000 -u 1000 www

RUN apt-get update \
    && apt-get install -y gnupg curl ca-certificates zip unzip git supervisor mysql-client \
    && mkdir -p ~/.gnupg \
    && chmod 600 ~/.gnupg \
    && apt-key adv --homedir ~/.gnupg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E5267A6C \
    && echo "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main" > /etc/apt/sources.list.d/ondrej-ubuntu-php-focal.list \
    && apt-get update \
    && apt-get install -y php7.4-cli php7.4-curl php7.4-gd php7.4-mysql php7.4-mbstring php7.4-xml php7.4-zip php7.4-bcmath \
        php7.4-intl php7.4-readline php7.4-msgpack php7.4-igbinary php7.4-redis libphp7.4-embed php7.4-sqlite3 \
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && curl -sL https://nginx.org/keys/nginx_signing.key | apt-key add - \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#RUN composer install --no-scripts --no-autoloader

EXPOSE 80
